### ISSUE TITLE
Package android does not belong to 2000

### ISSUE THREAD

**Issue by vvb2060** [zhanghai/BeeShell#5]
```
|  Welcome to BeeShell 1.0.1
|  Powered by BeanShell 2.0b6
bsh> context.getSystemService(ConnectivityManager.class)
$1 = android.net.ConnectivityManager@13f10fc
bsh> $1.getActiveNetwork()
$2 = 102
bsh> $1.getNetworkCapabilities($2)
Sourced file: inline evaluation of: ``$1.getNetworkCapabilities($2);'' : Method Invocation $1.getNetworkCapabilities : at Line: 1 : in file: inline evaluation of: ``$1.getNetworkCapabilities($2);'' : $1 .getNetworkCapabilities ( $2 )

Target exception: java.lang.SecurityException: Package android does not belong to 2000

        at bsh.BSHMethodInvocation.eval(Unknown Source:117)
        at bsh.BSHPrimaryExpression.eval(Unknown Source:51)
        at bsh.BSHPrimaryExpression.eval(Unknown Source:1)
        at bsh.Interpreter.eval(Unknown Source:145)
        at bsh.Interpreter.eval(Unknown Source:34)
        at bsh.Interpreter.eval(Unknown Source:26)
        at b.a.a.a.y.a(Unknown Source:13)
        at me.zhanghai.android.beeshell.ShellMain.main(:6)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.SecurityException: Package android does not belong to 2000
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities(IConnectivityManager.java:2456)
        at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1385)
        at java.lang.reflect.Method.invoke(Native Method)
        at bsh.Reflect.invokeMethod(Unknown Source:43)
        at bsh.Reflect.invokeObjectMethod(Unknown Source:45)
        at bsh.Name.invokeMethod(Unknown Source:138)
        at bsh.BSHMethodInvocation.eval(Unknown Source:57)
        ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7631)
        at com.android.server.ConnectivityService.getNetworkCapabilities(ConnectivityService.java:1666)
        at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:978)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)


```

**Comment by zhanghai** [comment]
Will this have a similar problem like in https://github.com/topjohnwu/libsu/pull/141/files ?

**Comment by zhanghai** [comment]
Update: Discussed with @vvb2060 and actually the important bit is `opPackageName` - using `createPackageContext` alone won't fix the issue.

**Comment by zhanghai** [comment]
Fixed.
